<?php
/**
 * This file is generated by WP Starter package, and contains base configuration of the WordPress.
 *
 * All the configuration constants used by WordPress are set via environment variables.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 *
 */
use WeCodeMore\WpStarter\Env\WordPressEnvBridge;

/** Composer autoload. */
require_once realpath(__DIR__ . '/vendor/autoload.php');

/** A reference to `.env` folder path. */
define('WPSTARTER_PATH', realpath(__DIR__ . '/'));

/**
 * Define all WordPress constants from environment variables.
 * Environment variables will be loaded from file, unless `WPSTARTER_ENV_LOADED` env var is already
 * setup e.g. via webserver configuration.
 * In that case all environment variables are assumed to be set.
 * Environment variables that are set in the *real* environment (e.g. via webserver) will not be
 * overridden from file, even if `WPSTARTER_ENV_LOADED` is not set.
 */
$envLoader = '1'
    ? WordPressEnvBridge::buildFromCacheDump(WPSTARTER_PATH . WordPressEnvBridge::CACHE_DUMP_FILE)
    : new WordPressEnvBridge();

if (!$envLoader->hasCachedValues()) {
    $envLoader->load('.env', WPSTARTER_PATH);
    $envName = $envLoader->read('WP_ENV') ?? $envLoader->read('WORDPRESS_ENV');
    if ($envName && $envName !== 'example') {
        $envLoader->loadAppended(".env.{$envName}", WPSTARTER_PATH);
    }
    $envLoader->setupConstants();
}

isset($envName) or $envName = $envLoader->read('WP_ENV') ?? $envLoader->read('WORDPRESS_ENV');

if (
    $envName
    && file_exists(WPSTARTER_PATH . "/{$envName}.php")
    && is_readable(WPSTARTER_PATH . "/{$envName}.php")
) {
    require_once WPSTARTER_PATH . "/{$envName}.php";
}

/** Set optional database settings if not already set. */
defined('DB_HOST') or define('DB_HOST', 'localhost');
defined('DB_CHARSET') or define('DB_CHARSET', 'utf8');
defined('DB_COLLATE') or define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 */
defined('AUTH_KEY') or define('AUTH_KEY', '/K$Ps[QCFXGh&w0e#?wdbo-z1|@zqG^&Mk=a#@o`Go=Bu1(etuO^7@lz?4aop Zs');
defined('SECURE_AUTH_KEY') or define('SECURE_AUTH_KEY', '$j7zI$HTjB:[0{n3c/[ %J!{geFp&Zu@ JB<o-OC75Si=+~eZ56(F;%.n&1o>geG');
defined('LOGGED_IN_KEY') or define('LOGGED_IN_KEY', 'C@ojOv qks0)a;o`w$!`K[6uv]F$j@[H<y,rdk}Au<2W@0>1<E%Q(>ZTp|-Bzx}x');
defined('NONCE_KEY') or define('NONCE_KEY', 'qg%OT5HdjO*H#*z~5I?}t@1<3Ko8[u#f)do>Qx p2Sdtw2o@t0/gGYQ/+FTJN[Fw');
defined('AUTH_SALT') or define('AUTH_SALT', 'eFX-T?gSEgX3QAa-s!_UIv4h}?rPOctv=OTkoRf~3s8fC$i3UFb$$~9~@wUNgfxR');
defined('SECURE_AUTH_SALT') or define('SECURE_AUTH_SALT', 'oFx,^d;{=g5p4i8x!e[c;cv{DC>Up$LH.s4;&Qhp-,,YWvkNsMv{G|BwGpm^v}a8');
defined('LOGGED_IN_SALT') or define('LOGGED_IN_SALT', 'm2/:Dwm(@6&8R7g*Tq>u*jVK+h2/m~Ve)>;9sb[?dtSNqQ%?M*bsy [D9(1.=Mg7');
defined('NONCE_SALT') or define('NONCE_SALT', '|11?y<D2[$d=0`J&OAk,?[9Iv/wh`L&/XQQ(D(Swc>31 ,N!fO9K@K)Bf_ooGR{F');

/**#@-*/

/**
 * WordPress Database Table prefix.
 */
global $table_prefix;
$table_prefix = $envLoader->read('DB_TABLE_PREFIX') ?: 'wp_';

/** Absolute path to the WordPress directory. */
defined('ABSPATH') or define('ABSPATH', realpath(__DIR__ . '/wordpress') . '/');

/** Load plugin.php early, so we can call `add_action` below. */
require_once ABSPATH . 'wp-includes/plugin.php';

/**
 * Load early hooks file if any.
 * Early hooks file allows to add hooks that are triggered before plugins are loaded, e.g.
 * "enable_loading_advanced_cache_dropin" or to just-in-time define configuration constants.
 */
if (
    ''
    && file_exists(__DIR__ . '')
    && is_readable(__DIR__ . '')
) {
    require_once __DIR__ . '';
}

/** Environment-aware settings. Be creative, but avoid having sensitive settings here. */
switch ($envName) {
    case 'local':
    case 'development':
        defined('WP_DEBUG') or define('WP_DEBUG', true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', true);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', false);
        defined('SAVEQUERIES') or define('SAVEQUERIES', true);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', true);
        defined('WP_DISABLE_FATAL_ERROR_HANDLER') or define('WP_DISABLE_FATAL_ERROR_HANDLER', true);
        break;
    case 'staging':
        defined('WP_DEBUG') or define('WP_DEBUG', true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', true);
        defined('SAVEQUERIES') or define('SAVEQUERIES', false);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', true);
        break;
    case 'production':
    default:
        defined('WP_DEBUG') or define('WP_DEBUG', false);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', false);
        defined('SAVEQUERIES') or define('SAVEQUERIES', false);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', false);
        break;
}
if ($envName === 'local' && !defined('WP_LOCAL_DEV')) {
    define('WP_LOCAL_DEV', true);
}

/** Fix `is_ssl()` behind load balancers. */
if (
    $envLoader->read('WP_FORCE_SSL_FORWARDED_PROTO')
    && array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER)
    && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https'
) {
    $_SERVER['HTTPS'] = 'on';
}

/** Setting WP_HOME is not strictly required, but highly recommended. */
if (!defined('WP_HOME')) {
    $home = filter_var($_SERVER['HTTPS'] ?? '', FILTER_VALIDATE_BOOLEAN) ? 'https://' : 'http://';
    $home .= $_SERVER['SERVER_NAME'] ?? 'localhost';
    define('WP_HOME', $home);
    unset($home);
}

/** Set WordPress other URL / path constants not set via environment variables. */
defined('WP_SITEURL') or define('WP_SITEURL', rtrim(WP_HOME, '/') . '/wordpress');
defined('WP_CONTENT_DIR') or define('WP_CONTENT_DIR', realpath(__DIR__ . '/wp-content'));
defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/') . '/wp-content');

/** Register default themes inside WordPress package wp-content folder. */
if (filter_var('false', FILTER_VALIDATE_BOOLEAN)) {
    add_action(
        'plugins_loaded',
        static function () {
            register_theme_directory(ABSPATH . 'wp-content/themes');
        },
        0
    );
}

/** Allow changing admin color scheme. Useful to distinguish environments in the dashboard. */
add_filter(
    'get_user_option_admin_color',
    static function ($color) use ($envLoader) {
        return $envLoader->read('WP_ADMIN_COLOR') ?: $color;
    },
    999
);

/** On shutdown we dump environment so that on subsequent requests we can load it faster */
if ('1' && $envLoader->isWpSetup()) {
    register_shutdown_function(
        static function () use ($envLoader, $envName) {
            $skipCache = apply_filters('wpstarter.skip.cache-env', $envName === 'local', $envName);
            $skipCache or $envLoader->dumpCached(WPSTARTER_PATH . WordPressEnvBridge::CACHE_DUMP_FILE);
        }
    );
}

unset($envName, $cacheEnv);

###################################################################################################
#  I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion.  #
#                 I watched C-beams glitter in the dark near the Tannhauser gate.                 #
#            All those moments will be lost in time, like tears in rain. Time to die.             #
###################################################################################################

/* That's all, stop editing! Happy blogging. */

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
