<?php
/**
 * This file is generated by WP Starter package, and contains base configuration of the WordPress.
 *
 * All the configuration constants used by WordPress are set via environment variables.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 *
 */
use WeCodeMore\WpStarter\Env\WordPressEnvBridge;

/** Composer autoload. */
require_once realpath(__DIR__ . '/vendor/autoload.php');

/** A reference to `.env` folder path. */
define('WPSTARTER_PATH', realpath(__DIR__ . '/'));

/**
 * Define all WordPress constants from environment variables.
 * Environment variables will be loaded from file, unless `WPSTARTER_ENV_LOADED` env var is already
 * setup e.g. via webserver configuration.
 * In that case all environment variables are assumed to be set.
 * Environment variables that are set in the *real* environment (e.g. via webserver) will not be
 * overridden from file, even if `WPSTARTER_ENV_LOADED` is not set.
 */
$envLoader = '1'
    ? WordPressEnvBridge::buildFromCacheDump(WPSTARTER_PATH . WordPressEnvBridge::CACHE_DUMP_FILE)
    : new WordPressEnvBridge();

if (!$envLoader->hasCachedValues()) {
    $envLoader->load('.env', WPSTARTER_PATH);
    $envName = $envLoader->read('WP_ENV') ?? $envLoader->read('WORDPRESS_ENV');
    if ($envName && $envName !== 'example') {
        $envLoader->loadAppended(".env.{$envName}", WPSTARTER_PATH);
    }
    $envLoader->setupConstants();
}

isset($envName) or $envName = $envLoader->read('WP_ENV') ?? $envLoader->read('WORDPRESS_ENV');

if (
    $envName
    && file_exists(WPSTARTER_PATH . "/{$envName}.php")
    && is_readable(WPSTARTER_PATH . "/{$envName}.php")
) {
    require_once WPSTARTER_PATH . "/{$envName}.php";
}

/** Set optional database settings if not already set. */
defined('DB_HOST') or define('DB_HOST', 'localhost');
defined('DB_CHARSET') or define('DB_CHARSET', 'utf8');
defined('DB_COLLATE') or define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 */
defined('AUTH_KEY') or define('AUTH_KEY', '_Mx4>jo<h%)*~mRdBSp@n7+G7x t1)/9Se8{?RDbZJzZg6<TPBc-Y.6.XsF9m4<H');
defined('SECURE_AUTH_KEY') or define('SECURE_AUTH_KEY', '1HEZQO&/$wC3s[88-lBYvSS>qX=B+@B._.NE}D=6ngpt0EI>-J]40]kx[f|-kMDW');
defined('LOGGED_IN_KEY') or define('LOGGED_IN_KEY', 'G,&Jz=!_ahX,Ul6+y|ZT&%2^hxP{lefa6cY/40dQA<vis`Pq5lAu1E_O%Gm4bU5#');
defined('NONCE_KEY') or define('NONCE_KEY', 'I(X{~6M~x6sJ~>U<=nCQN#56`fr@3wv#<Ng{0 T)k? .q>{fO~=%Cz]5i&lTS@&C');
defined('AUTH_SALT') or define('AUTH_SALT', 'uo#L^mWV^lKLeGdH+He=CzZ`,n(-!)n2+I|/zF;g2-4`KS&p)2cqkEhEw].jvvP/');
defined('SECURE_AUTH_SALT') or define('SECURE_AUTH_SALT', '-1IsOiSYozvVh_#UPM5YLwAt(ddVv6vI-Q6<83hG_%p uRa?f%1Z3x`Bw>Tdz7e:');
defined('LOGGED_IN_SALT') or define('LOGGED_IN_SALT', '+|~e@>k(,X4tv)^#s7j%0&S{bAVGg4;{:Bl]>5hqb&;EDvKI`:q7,ZVbDai%p7$m');
defined('NONCE_SALT') or define('NONCE_SALT', 'ggrd#/,r>J&KZy*Mg}I(bs:R6eqZG@VK?c{2+m2<f`#(#pI|ZJ0ShWtDuYEzr~Ur');

/**#@-*/

/**
 * WordPress Database Table prefix.
 */
global $table_prefix;
$table_prefix = $envLoader->read('DB_TABLE_PREFIX') ?: 'wp_';

/** Absolute path to the WordPress directory. */
defined('ABSPATH') or define('ABSPATH', realpath(__DIR__ . '/wordpress') . '/');

/** Load plugin.php early, so we can call `add_action` below. */
require_once ABSPATH . 'wp-includes/plugin.php';

/**
 * Load early hooks file if any.
 * Early hooks file allows to add hooks that are triggered before plugins are loaded, e.g.
 * "enable_loading_advanced_cache_dropin" or to just-in-time define configuration constants.
 */
if (
    ''
    && file_exists(__DIR__ . '')
    && is_readable(__DIR__ . '')
) {
    require_once __DIR__ . '';
}

/** Environment-aware settings. Be creative, but avoid having sensitive settings here. */
switch ($envName) {
    case 'local':
    case 'development':
        defined('WP_DEBUG') or define('WP_DEBUG', true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', true);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', false);
        defined('SAVEQUERIES') or define('SAVEQUERIES', true);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', true);
        defined('WP_DISABLE_FATAL_ERROR_HANDLER') or define('WP_DISABLE_FATAL_ERROR_HANDLER', true);
        break;
    case 'staging':
        defined('WP_DEBUG') or define('WP_DEBUG', true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', true);
        defined('SAVEQUERIES') or define('SAVEQUERIES', false);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', true);
        break;
    case 'production':
    default:
        defined('WP_DEBUG') or define('WP_DEBUG', false);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', false);
        defined('SAVEQUERIES') or define('SAVEQUERIES', false);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', false);
        break;
}
if ($envName === 'local' && !defined('WP_LOCAL_DEV')) {
    define('WP_LOCAL_DEV', true);
}

/** Fix `is_ssl()` behind load balancers. */
if (
    $envLoader->read('WP_FORCE_SSL_FORWARDED_PROTO')
    && array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER)
    && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https'
) {
    $_SERVER['HTTPS'] = 'on';
}

/** Setting WP_HOME is not strictly required, but highly recommended. */
if (!defined('WP_HOME')) {
    $home = filter_var($_SERVER['HTTPS'] ?? '', FILTER_VALIDATE_BOOLEAN) ? 'https://' : 'http://';
    $home .= $_SERVER['SERVER_NAME'] ?? 'localhost';
    define('WP_HOME', $home);
    unset($home);
}

/** Set WordPress other URL / path constants not set via environment variables. */
defined('WP_SITEURL') or define('WP_SITEURL', rtrim(WP_HOME, '/') . '/wordpress');
defined('WP_CONTENT_DIR') or define('WP_CONTENT_DIR', realpath(__DIR__ . '/wp-content'));
defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/') . '/wp-content');

/** Register default themes inside WordPress package wp-content folder. */
if (filter_var('false', FILTER_VALIDATE_BOOLEAN)) {
    add_action(
        'plugins_loaded',
        static function () {
            register_theme_directory(ABSPATH . 'wp-content/themes');
        },
        0
    );
}

/** Allow changing admin color scheme. Useful to distinguish environments in the dashboard. */
add_filter(
    'get_user_option_admin_color',
    static function ($color) use ($envLoader) {
        return $envLoader->read('WP_ADMIN_COLOR') ?: $color;
    },
    999
);

/** On shutdown we dump environment so that on subsequent requests we can load it faster */
if ('1' && $envLoader->isWpSetup()) {
    register_shutdown_function(
        static function () use ($envLoader, $envName) {
            $skipCache = apply_filters('wpstarter.skip.cache-env', $envName === 'local', $envName);
            $skipCache or $envLoader->dumpCached(WPSTARTER_PATH . WordPressEnvBridge::CACHE_DUMP_FILE);
        }
    );
}

unset($envName, $cacheEnv);

###################################################################################################
#  I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion.  #
#                 I watched C-beams glitter in the dark near the Tannhauser gate.                 #
#            All those moments will be lost in time, like tears in rain. Time to die.             #
###################################################################################################

/* That's all, stop editing! Happy blogging. */

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
